[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'forge-cache'
solc = '0.8.20'

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC}"
blast_sepolia = "${BLAST_SEPOLIA_RPC}"

[etherscan]
base_sepolia = {key = "${BASESCAN_API_KEY}", url="https://api-sepolia.basescan.org/api"}
blast_sepolia = {key = "${BLASTSCAN_API_KEY}", url="https://api-sepolia.blastscan.io/api"}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config